// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smooth.Shop.Infrastructure.Data;

#nullable disable

namespace Smooth.Shop.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SmoothWebDbContext))]
    partial class SmoothWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smooth.Shop.Domain.Models.NewMedium", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UploadFinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("UploadStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<long>("UploadTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<string>("UploadedFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(12);

                    b.HasKey("Id");

                    b.ToTable("NewMedia", "shop");
                });
#pragma warning restore 612, 618
        }
    }
}
